# Use this file to store secrets like usernames and passwords.
# Learn more at https://www.home-assistant.io/docs/configuration/secrets/

# Postgres connection string
psql_string: "postgresql://homeassistant:admin@database/homeassistant"
